export const MAIN_NAV_ITEMS = [
  {
    to: "/",
    label: "Home",
    footerShortLabel: "Home",
    fnKeyLabel: "F3",
    digitKey: "1",
    barLabel: "Home",
    barHotkeyIndex: 0,
  },
  {
    to: "/portfolio",
    label: "Portfolio",
    footerShortLabel: "Portifolio",
    fnKeyLabel: "F2",
    digitKey: "2",
    barLabel: "Portifolio",
    barHotkeyIndex: 0,
  },
  {
    to: "/about",
    label: "About",
    footerShortLabel: "About Me",
    fnKeyLabel: "F1",
    digitKey: "3",
    barLabel: "About Me",
    barHotkeyIndex: 0,
  },
  {
    to: "/contact",
    label: "Contact",
    footerShortLabel: "Contact",
    fnKeyLabel: "F4",
    digitKey: "4",
    barLabel: "Contact",
    barHotkeyIndex: 0,
  },
] as const;
